import { FormElements } from "../pages/FormBuilder/type";

export const MOCK_DATA_VALUES = {
  firstName: "Albin",
  lastName: "Joseph",
  email: "albin.joseph@example.com",
  phone: "+1 987-654-3210",
  designation: "Software Engineer",
  department: "Engineering",
  employeeId: "EMP12345",
  joiningDate: "2025-05-01",
  workLocation: "San Francisco Office",
  employmentType: "Full-time",
  reportingManager: "Sarah Williams",
  laptopRequired: true,
  emergencyContactName: "Maria Joseph",
  emergencyContactPhone: "+1 123-456-7890",
  emergencyAddress: "123 Main Street, Springfield, USA",
  permanentAddress: "456 Elm Street, Springfield, USA",
  currentAddress: "456 Elm Street, Springfield, USA",
  bloodGroup: "O+",
  dateOfBirth: "1995-08-15",
  gender: "male",
  maritalStatus: "Single",
  nationality: "American",
  aadharNumber: "1234-5678-9123",
  panNumber: "ABCDE1234F",
  passportNumber: "N1234567",
  bankAccountNumber: "123456789012",
  ifscCode: "HDFC0001234",
  officialEmail: "albin.joseph@company.com",
  personalEmail: "albin.personal@example.com",
  alternatePhone: "+1 222-333-4444",
  dob: "06-02-1997",
  linkedinProfile: "https://www.linkedin.com/in/albinjoseph",
  githubProfile: "https://github.com/albinjoseph",
  additionalNotes: "Needs MacBook Pro setup and software installation.",
  tshirtSize: ["s", "m", "l"],
  preferredName: "Albin Britto Santiagu",
  baseSalary: "180000",
  bonusEligible: "Yes",
  bonusAmount: "100000",
  currency: "Rupee",
  remoteWorkAllowed: "Yes",
  workHours: "8",
  emergencyContactRelation: "Wife",
  medicalConditions: "Good and healthy",
  healthInsurance: "Yes",
  retirementPlan: "No",
  mealPreferences: "NoN Veg",
  languageKnown: ["html"],
};

export const FORM_ELEMENTS: FormElements = {
  basic: {
    title: "Basic",
    elements: [
      {
        id: "heading",
        name: "heading",
        label: "Heading",
        Icon: "FontSizeOutlined",
        type: "heading",
      },
      {
        label: "Single Line",
        Icon: "UserOutlined",
        type: "singleline",
        id: "singleLine",
        name: "singleLine",
      },
      {
        Icon: "EnvironmentOutlined",
        label: "MultiLine",
        type: "multiline",
        id: "multiline",
        name: "multiline",
      },
      {
        id: "email",
        label: "Email",
        Icon: "MailOutlined",
        type: "email",
        name: "email",
      },
      {
        label: "Phone",
        Icon: "PhoneOutlined",
        type: "number",
        id: "phone",
        name: "phone",
      },
      {
        id: "date",
        label: "Date Picker",
        Icon: "CalendarOutlined",
        type: "datepicker",
      },
      {
        id: "singleChoice",
        label: "Single Choice",
        Icon: "CheckCircleOutlined",
        type: "singlechoice",
        name: "singleChoice",
        options: [
          {
            label: "option 1",
            value: "option 1",
          },
          {
            label: "option 2",
            value: "option 2",
          },
          {
            label: "option 3",
            value: "option 3",
          },
        ],
      },
      {
        id: "multipleChoice",
        label: "Multiple Choice",
        Icon: "CheckSquareOutlined",
        type: "multichoice",
        name: "multipleChoice",
        options: [
          {
            label: "option 1",
            value: "option 1",
          },
          {
            label: "option 2",
            value: "option 2",
          },
          {
            label: "option 3",
            value: "option 3",
          },
        ],
      },
      {
        id: "dropdown",
        label: "DropDown",
        Icon: "DownSquareOutlined",
        type: "select",
        name: "dropdown",
        options: [
          {
            label: "option 1",
            value: "option 1",
          },
          {
            label: "option 2",
            value: "option 2",
          },
          {
            label: "option 3",
            value: "option 3",
          },
        ],
      },
      {
        id: "6609fdcc-3d6f-4ff6-bf58-97b34fded5e6",
        label: "Number",
        Icon: "NumberOutlined",
      },
      {
        id: "5b1773cf-c3e5-4e13-9e60-71e0c59d88fc",
        label: "Rating",
        Icon: "StarOutlined",
        type: "rate",
        name: "rate",
      },
      {
        id: "6d11773c-7f47-41d4-b3a9-89862237e49b",
        label: "Image",
        Icon: "PictureOutlined",
      },
    ],
  },
};
